### ISSUE TITLE
Taming Needs More Work

### ISSUE THREAD

**Issue by Coraline77447** [MarkusBordihn/BOs-Player-Companions#1]
**Describe the bug**
I can't tame more than just one companion since I've tried to tame a; Welsh Corgi, Roosterz and Pig.
Already have one of the two types of the fairy (blonde I think?) but I already know that I cant tame another fairy due to the taming still in development but now I cant tame more than just one companion in general.

**To Reproduce**
1. Tame any one of the current companions
2. Try to tame a different  kind of companion
3. Literally see the entity vanish right before your eyes into thin air without a trace and no corresponding item of the second companion in the inventory.

**Expected behavior**
Being able to tame more than just one companion

**Screenshots**
N/A

**Debugging**
[latest.log](https://github.com/MarkusBordihn/BOs-Player-Companions/files/8238121/latest.log)

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
N/A

**Additional context**
Even tho this problem may have been fixed already but apparently the fix may have cause a much bigger problem than the last..Now I can't tame no more than one companion at a time when I want the fairy (or both the default one and the redhead one)(healer(s), the Welsh Corgi (supporter), and the rooster (guard)...

As I've mentioned above, I'll provide the latest log when I'm finished with my current play session which is still going right now. I am planning on stopping in 15 or so minutes since I've been playing for at least 3-4+ hours already...

**Comment by MarkusBordihn** [comment]
Thanks for the report. Unfortunately I'm not really able to reproduce the issue on my side see:

![image](https://user-images.githubusercontent.com/12183293/158030739-8782d4c4-afba-4064-a314-3a355a55efbd.png)

Each companion has his own unique ID and only this ID is stored inside the companion item.
Which mean it's sound like that some optimization mod kills entities in a close range or adjusting the entity chunk loading.

Could you please try the following to isolate the issue more in detail:
- Create a new world with creative mode and use the spawn eggs to spawn the companion, did they vanish here as well ?
- If not, try to tame these companions and run "/companions list" to see if they are registered to your player?

I will try to add some additional debug information to the log, but could not really reproduce the issue standalone or with my reference mod pack on my side. :(

**Comment by Coraline77447** [comment]
I currently have two 1.18.1 worlds but they're both different worlds despite them having nearly the same mods and nearly the same amount of mods.

Right now I'm looking in Cora Tinkers' saves folder in it's data folder in Player Companions data folder for the world Cora Tinkers' and this is what I'm seeing;

![Screenshot (50)](https://user-images.githubusercontent.com/72243304/158162878-3d34d87a-5574-40c6-9ba6-07a695e5a230.png)

In there there's my; fairy, welsh corgi, pig, and rooster. The pig and rooster were just test subjects to see If they're bugged as well and I did confirm that they too disappeared when I tamed them.

I have a few questions; 

What would happen if I were to delete the data for my welsh corgi, pig, and rooster? Since I don't want the game to constantly keep telling me that they're not registered even tho I've tamed them and everything.

Were you testing this issue in a dev environment or normal environment out of dev environment?

Since it's obvious that the problem won't exist inside dev environment but outside of that type of environment the problem exists.

Not everybody may encounter the issue that I face with Player Companions BUT that doesn't mean that I may be the only one who's experiencing this issue

"It's sound like that some optimization mod kills entities in a close range or adjusting the entity chunk loading."

I do have some optimization mods installed to help my games overall performace, even with less than 100 mods my performance isn't where it should be and after say 2 or 3 hours of playing the game starts to shutter, stutter, and lag heavily, despite having 8gb of RAM on my machine, using Optifine along with Betterfpsdist, Farsight, Ferrite Core, Ksyxis, and Modern UI that my game still lags badly after 3+ hours, especially when loading into new unexplored chunks.

Could one of the optimization mods that I'm currently using be causing this issue? If so then which one?
I could try to find out for myself but I don't feel like that I have enough time to do that since the only time that I would have to sift through my mods list(s) is for when the game crashes and a mod is causing the crash but I haven't ran into any crashes yet but I hope to not run into any crashes however.

Even tho I wouldn't be testing this issue out to figure out which one of the optimization mods is causing this issue but I've just decided with myself that I'll make a test world with only the optimization mods with Player Companions and will do everything that you've said by starting the test world in creative mode and bring in their spawn egs and taming items and one by one will be taking out which mod isn't causing this till the perpetrator caught and won't be using sad optimization mod ever again since it conflicts with Player Companions. 

If it's Optifine then I don't know what to do to replace it since no other optimization mod could ever come close to it, and some mods as well as resource packs needs optifine sadly....

**Comment by MarkusBordihn** [comment]
Thanks for the update. I released a new version https://www.curseforge.com/minecraft/mc-mods/player-companions/files/3693143 which includes some additional log output to see what it happening.

**My ask:**
Please try to reproduce the issue with this updated version (even without Ksyxis) and send me the log file if you are still see any issues.

**Answers to your questions:**

The data file includes all of the stats of the tamed companion per player. If you have upgraded from an older version it could be that the data file is corrupt and you need to delete it.

I always testing my mods in different environment like:

- Developer Environment (with Java Debugger / with 10 Mods)
- CurseForge Launcher (with CurseForge Forge Client / with 100 Mods)
- Local Server running in my network (Forge Client / with 200 Mods)
- Live Server running by a ISP with 10 - 20 live players (with 250 Mods)

There are mod developers which are using core and/or mixin modification (because they are easier to implement), which could cause conflicts in other mods.
It's always hard to isolate such issues, because they are not easy to spot or to reproduce.

Human Companions should work fine, I added some fix and don't see any issues with it.
I personally never heart about Ksyxis as performance mod and could say that I have some experience in this area.

You could try https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks which is not using any core modding or mixin and handles tasks like entity spawning and item spawning which helps in most cases.
You can be sure that this mod is compatible because I use it in all of my tests.
