### ISSUE TITLE
change ownership of companion

### ISSUE THREAD

**Issue by DentyTxR** [MarkusBordihn/BOs-Player-Companions#10]
could be a nice feature, the reason im asking this is because I had my UUID changed and I no longer can control my companions, tried modifying data with NBT but I couldn't find anything related to the owners UUID

**Comment by MarkusBordihn** [comment]
Unfortunately that's not so easy as long the companion is still alive in the world, because the entity itself is also stored inside the world data which you should not modify.

The best way is to use an NBT editor to change the corresponding values.
![image](https://user-images.githubusercontent.com/12183293/190806466-69131f19-6e21-4f46-a45c-f2bce9e2ad19.png)

You need to change the following two entries inside the `data/player_companions.dat` file:

- data.Companions.[companion].Owner
- data.Companions.[companion].EntityData.Owner

The UUID is encoded as an int-array. There are some converter which allows an easy conversion like:
https://www.soltoder.com/mc-uuid-converter/

Just enter your new username and you will get the UUID in the right format under `UUID: [I;`.

It's important that you kill your companion (if it still in the world) and to end the game before modifying the data, to make sure that there are not any artifacts left with mismatching data.
