### ISSUE TITLE
Player companions causes Internal Server Error

### ISSUE THREAD

**Issue by msdomtv** [MarkusBordihn/BOs-Player-Companions#2]
**Describe the bug**
After a player dropped a Corgi, my character was trying to pick it up and then we both errored off the server with Internal Server Error and could not log back into the server. Server is hosted with Shockbyte

**To Reproduce**
1. Get Corgis
2. Upgrade them to Allthemodium armor
3. Droped one to be picked up

**Expected behavior**
Server to not crash or crash clients out of connecting to server. 

**Screenshots**

**Debugging**
I attached a server error stack trace.
[errorlogCompanions.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/8345169/errorlogCompanions.txt)

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
[companionsCrashModList.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/8345173/companionsCrashModList.txt)

**Additional context**

**Comment by MarkusBordihn** [comment]
Thanks for the report, this issue was already fixed some weeks ago. 

It's seems that  you are using an old version of the player companions mod.
Please update the mod to version [player_companions_1.18.1-0.8.0.jar](https://www.curseforge.com/minecraft/mc-mods/player-companions/files/3709727) which should fix the error in the provided error logs.

**Comment by msdomtv** [comment]
@MarkusBordihn Okay sounds good thank you!!
