### ISSUE TITLE
Dobutsu without waiting sound causing crashes.

### ISSUE THREAD

**Issue by M25R4PTOR** [MarkusBordihn/BOs-Player-Companions#25]
**Describe the bug**
Crash Game Like https://github.com/MarkusBordihn/BOs-Player-Companions/issues/24 but its dobutsu in minecraft 1,20,1

**To Reproduce**
1. Open World LAN
2. Dobutsu friends stay sit
3. Wait and the game crash

**Expected behavior**
No crash xD

**Debugging**
[crash-2023-10-05_20.50.48-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12822698/crash-2023-10-05_20.50.48-server.txt)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. I implemented a patch which should be live in the next few hours.

Please let me know if version 6.1.1 is fixing the crashes, if yes I will roll out the fix for all other versions as well. Thanks.

**Comment by M25R4PTOR** [comment]
Tonight we will test it hard.

I would like to ask you a question that has nothing to do with the mod.

When I open the world on LAN my friend can see it, but when he tries to access it most of the time it doesn't enter and says "timed out".

Is there any way to fix it?

To be able to play it takes me more than 20 minutes until it manages to connect, once connected it works perfectly.

Tomorrow I will comment if the patch works well if I can play tonight

Thanks for everything!!

**Comment by MarkusBordihn** [comment]
> When I open the world on LAN my friend can see it, but when he tries to access it most of the time it doesn't enter and says "timed out".
> 
> Is there any way to fix it?
> 
> To be able to play it takes me more than 20 minutes until it manages to connect, once connected it works perfectly.

There could be several reasons for this. But in general you should check the following:

- Ping the LAN IP address from both sides to see if there are any packet lost.
- Make sure you are using an official client.
- Check the debug.log and/or latest.log on both sides, normally it will tell you if mods are missing or give you some hints why a connection is time out.
- Test with a real dedicated server or use something like https://aternos.org/ to see if you have the same issues here.
- Test without / with mods, there could be some mods which causing this issue because they are not build for servers and for singleplay only.

**Comment by M25R4PTOR** [comment]
I play opening singleplayer world on lan.

The ping is done perfectly.

Out of every 40 attempts my friend manages to enter once because the waiting time has expired, but when he enters it works perfectly.

I saw a mod that increases the login time to 900 seconds but it is not in version 1.20.1. Do you know a way to solve it?

**Comment by M25R4PTOR** [comment]
I tested it overnight and it works perfectly.

Thanks for everything!
